- Makefile
- entry.cpp
- generate_dict.cpp
- modules/evercrypt/Makefile
- modules/evercrypt/module.cpp
- modules/evercrypt/module.h
This PR adds a module for [EverCrypt](https://github.com/project-everest/hacl-star/releases/tag/evercrypt-v0.1alpha1). At the moment, the module implements only the `opDigest`, `opHMAC`, and `opHKDF` targets.
The `Makefile` expects the `EVERCRYPT_A_PATH`, `KREMLIN_A_PATH`, `EVERCRYPT_INCLUDE_PATH`, and `KREMLIN_INCLUDE_PATH` environment variables be set and a pre-compiled _generic_ C distribution of EverCrypt v0.1alpha1. For instance, if the EverCrypt v0.1alpha1 archive has been extracted to `$SRC/evercrypt` and compiled,
```bash
export EVERCRYPT_A_PATH="$SRC/evercrypt/dist/generic/libevercrypt.a"
export KREMLIN_A_PATH="$SRC/evercrypt/dist/kremlin/kremlib/dist/minimal/*.o"
export EVERCRYPT_INCLUDE_PATH="$SRC/evercrypt/dist"
export KREMLIN_INCLUDE_PATH="$SRC/evercrypt/dist/kremlin/include" …
```
> EverCrypt module

- modules/libgcrypt/module.cpp
`process()` could return a value even when the main encryption/decryption loop failed.
This causes e.g. encryption to return a truncated ciphertext when the output buffer is too short and the loop iterates at least once, setting `ret`.
> libgcrypt: fixes process() not returning std:nullopt when main loop fails

- README.md
- docs/building.md
- docs/nss.md
- docs/running.md
This includes:
- Rewording and restructuring docs/building.md
- Introducing NSS-specific build instructions
- Add docs/running.md to give an overview of libFuzzer usage
- Update the README to point at the new documentation
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`
> Improve documentation on Cryptofuzz

- gen_repository.py
Fedora systems are getting to the point of not shipping Python 2 at all;
for now it is still available from the repositories but not shipped by
default. Also, `/usr/bin/python` isn't guaranteed to be Python 2 any more:
[`python-unversioned-command` on Fedora 31](https://fedoraproject.org/wiki/Changes/Python_means_Python3#Python_command) ships this as Python 3.
Make `gen_repository.py` Python 3 compatible and set that as the default
in the shebang, but retain Python 2 compatibility.
@guidovranken Happy to modify this however you'd prefer (e.g., if you'd prefer to make the shebang Python 2). 
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`
> Make gen_repository Python 2/Python 3 compatible

- modules/wolfcrypt/bn_ops.cpp
In wolfCrypt, we changed the return code on integer.c:mp_exch() from void to int. Needed to update the assertion.
> Update bn_ops with change in mp_exch for wolfCrypt

- docs/wolfcrypt.md
- modules/wolfcrypt-openssl/module.cpp
1. Remove `--enable-hc128` from the wolfCrypt build doc.
2. Remove idea-cbc test from wolfcrypt-openssl module.
> wolfCrypt: HC128 and IDEA algo removal

- modules/openssl/module.cpp
[AWS-LC](https://github.com/awslabs/aws-lc) is a general-purpose cryptographic library based on code from the Google BoringSSL project and the OpenSSL project. The ciphers/digests enabled by `CRYPTOFUZZ_BORINGSSL` are applicable to AWS-LC.
AWS-LC moved `|EVP_aes_256_xts|` code from `libdecrepit` to `libcrypto`. `CRYPTOFUZZ_AWSLC` is added to fuzz this cipher. 
Some debug statements were added inside `aes_xts_cipher` of AWS-LC. The statements got print out during fuzzing.
* I will submit new PRs to add more formal support of `CRYPTOFUZZ_AWSLC`. e.g.
* Expand `#if defined(CRYPTOFUZZ_BORINGSSL)` to `#if defined(CRYPTOFUZZ_BORINGSSL) || #if defined(CRYPTOFUZZ_AWSLC)`.
* Add related README.
> Fuzz |EVP_aes_256_xts| when |CRYPTOFUZZ_AWSLC| is defined.

- util.cpp
Build error was found when building cryptofuzz on `c6g.2xlarge`, which are powered by Arm-based AWS Graviton2 processors.
```
In file included from util.cpp:14:
./third_party/cpu_features/include/cpuinfo_x86.h:205:2: error: "Including cpuinfo_x86.h from a non-x86 target."
^
1 error generated.
```
> Avoid the build issue on arm.

- docs/openssl.md
This PR is the continue of https://github.com/guidovranken/cryptofuzz/pull/32, which planned to add `CRYPTOFUZZ_AWSLC` related doc.
* I dropped the plan of expanding `#if defined(CRYPTOFUZZ_BORINGSSL)` with `#if defined(CRYPTOFUZZ_BORINGSSL) || #if defined(CRYPTOFUZZ_AWSLC)` because aws-lc normally has the ciphers provided by boringssl.
Tested in https://github.com/guidovranken/cryptofuzz/pull/32
> Add CRYPTOFUZZ_AWSLC doc.

- modules/openssl/bn_ops.h
Added conditional reversal for AsUint64 to avoid reversing the value if platform is s390x, which is big-endian.
Closes Issue #39
> added conditional reversal in AsUint64

- modules/secp256k1/module.cpp
- modules/secp256k1/secp256k1_api.c
- modules/secp256k1/secp256k1_api.h
This was removed upstream, https://github.com/bitcoin-core/secp256k1/pull/1062, and is causing build failures downstream:
```bash
clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -DCRYPTOFUZZ_NO_OPENSSL -I /src/boost_1_74_0/ -DCRYPTOFUZZ_SECP256K1 -DCRYPTOFUZZ_TREZOR_FIRMWARE -DCRYPTOFUZZ_BOTAN -DCRYPTOFUZZ_BOTAN_IS_ORACLE -DCRYPTOFUZZ_BITCOIN -Wall -Wextra -std=c++17 -I include/ -I . -I fuzzing-headers/include -DFUZZING_HEADERS_NO_IMPL driver.o executor.o util.o entry.o tests.o operation.o datasource.o repository.o options.o components.o wycheproof.o crypto.o expmod.o mutator.o z3.o numbers.o mutatorpool.o ecc_diff_fuzzer_importer.o …
```
> libsecp256k1: remove secp256k1_fe_equal_var

- modules/libecc/Makefile
- modules/libecc/module.cpp
Hi,
We have changed the API headers place for `libecc`: these headers are now in the library path `include/libecc` folder (this modification is useful for the `meson` build system work in progress integration).
This calls for minor modifications in the `CryptoFuzz` dedicated module include paths and `Makefile`.
Regards,
> [libecc] Fix the CryptoFuzz libecc module with new headers source tree.

- modules/libecc/Makefile
- modules/libecc/module.cpp
Sorry for this duplicate PR, but PR #56 was not properly including the paths. This should work better (locally tested with OSS-Fuzz compilation).
> [libecc] Fix (again) inclusion paths in libecc module (fixing PR #56).

- generate_dict.cpp
generate_dict includes repository_map.h which uses the optional library.
If I had to guess this gets transitively included by other
files included by generate_dict depending on your distribution's libstdc.
Original error message:
```
./repository_map.h:633:10: error: no template named 'optional' in namespace 'std'
```
> Fix issue #54 regarding compilation of generate_dict

- docs/java.md
- modules/java/module.cpp
- The `jclass` type gets shadowed by a variable of the same name which
results in weird compilation issues if you try to use that type
elsewhere in the file.
- The non-JAVA_OSS_FUZZ build is broken. Conditionally restoring the
commented out code fixes this.
- Add some more documentation.
> Java Module fixes

- Makefile
There were three issues with the Makefile that could result in broken builds:
- repository_{tbl,map}.h files were missing as pre-requisites for a lot of the object files.
- Only repository_tbl.h was listed as a target of the gen_repository.py rule.
- The clean target did not clean all of the targets the Makefile builds.
This fixes these issues by...
- Defining variables for these two sets of target files and using them as appropriate.
- Using a pattern rule that matches most of the object files for consistency.
- Changing the gen_repository rule to use the group target syntax.
> Refactor Makefile to fix pre-requisites and clean target

- modules/secp256k1/module.cpp
- modules/secp256k1/secp256k1_api.c
- modules/secp256k1/secp256k1_api.h
This was removed upstream, https://github.com/bitcoin-core/secp256k1/pull/1184, and is causing build failures downstream:
```bash
clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -DCRYPTOFUZZ_NO_OPENSSL -I /src/boost_1_74_0/ -DCRYPTOFUZZ_SECP256K1 -DCRYPTOFUZZ_TREZOR_FIRMWARE -DCRYPTOFUZZ_BOTAN -DCRYPTOFUZZ_BOTAN_IS_ORACLE -DCRYPTOFUZZ_BITCOIN -Wall -Wextra -std=c++17 -I include/ -I . -I fuzzing-headers/include -DFUZZING_HEADERS_NO_IMPL bignum_fuzzer_importer.o botan_importer.o builtin_tests_importer.o components.o crypto.o datasource.o driver.o ecc_diff_fuzzer_exporter.o ecc_diff_fuzzer_importer.o entry.o executor.o expmod.o mutator.o …
```
> libsecp256k1: remove secp256k1_scalar_shr_int

- modules/secp256k1/module.cpp
- modules/secp256k1/secp256k1_api.c
- modules/secp256k1/secp256k1_api.h
This was renamed upstream in
https://github.com/bitcoin-core/secp256k1/commit/5005abee60ad03d2967c9aadf4e25d208c90d98a
and is causing build failures downstream:
```bash
clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=enum-constexpr-conversion -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION  -fprofile-instr-generate -fcoverage-mapping -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++ -DCRYPTOFUZZ_NO_OPENSSL -I /src/boost_1_84_0/ -DCRYPTOFUZZ_SECP256K1 -DCRYPTOFUZZ_TREZOR_FIRMWARE -DCRYPTOFUZZ_BOTAN -DCRYPTOFUZZ_BOTAN_IS_ORACLE -DCRYPTOFUZZ_BITCOIN -Wall -Wextra …
```
> libsecp256k1: remove secp256k1_scalar_get_bits

- modules/constantine/constantine_harness.nim
Accompanying upstream PR: https://github.com/mratsim/constantine/pull/432
In preparation to v0.1.0 Constantine had changes to its internals:
- https://github.com/mratsim/constantine/pull/399
- https://github.com/mratsim/constantine/pull/400
- https://github.com/mratsim/constantine/pull/402
And there is an extra renaming of internal scalar mul implementations in #431:
- https://github.com/mratsim/constantine/commit/cbce22632a0c799ac2879f2f688ed2ec454e7137#diff-9398921f79a9a16c6534f8038b5b3543653e1429c065eeb17ca06e86805c8314L151 and below
Note that with GCC-14.1 which is slowly being rolled out in distros, Nim was triggering the new incompatible pointer types error: https://forum.nim-lang.org/t/11587
Constantine works with Nim 2.0.8 which should be fully compatible with GCC 14.1
> fix(constantine): update following v0.1.0 refactor

- modules/secp256k1/secp256k1_api.c
Native 128-bit integers are not supported by 32-bit arm compilers.
> secp256k1: arm32 doesn't support native 128-bit integers

- docs/secp256k1.md
It was removed in https://github.com/bitcoin-core/secp256k1/pull/831, and results in:
```bash
configure: WARNING: unrecognized options: --with-bignum
```
> doc: remove `--with-bignum` from secp256k1 configure

- modules/botan/bn_ops.cpp
Probably should have been part of 687d3064c5cef2b0fe1f30824065a2f2c9c0bbd8.
The header was removed as part of https://github.com/randombit/botan/pull/4385, and it's inclusion is causing build issues downstream, i.e: https://github.com/google/oss-fuzz/pull/12659.
> botan: remove `botan/internal/curve_nistp.h` include
